### PR TITLE
Add syntax highlighting to readme code snippets

### PR DESCRIPTION
**Pull request by bronzehedwick**

### CODE REVIEW

**Comment by garris** [comment]
Hi @bronzehedwick.  Thanks for the PR!   Looks like there were a few of updates that clobbered some of your changes. Other than that everything looks good.  I don't know if you'll want to resolve those on your end.  Please let me know.   Thanks again.

**Comment by bronzehedwick** [comment]
Hey @garris, thanks for the quick review! I fixed the merge conflicts, so hopefully that all checks out.

**Comment by garris** [comment]
Beautiful -- thank you!   Cheers

**Comment by bronzehedwick** [comment]
:+1:

**Pull request merged**
