### PR TITLE
use resemble's more accurate rawMisMatchPercentage value

### LINKED ISSUE #477: misMatchThreshold of 0 still allows changes on large reference images
Nice work on Backstop!

We are diff'ing a project with a lot of data on a particular page. The reference image is quite large (1024x23046).

Even with a misMatchThreshold=0, we've noticed very small changes to the image will not fail the test. A single offset word, for example. 

We've tried other misMatchThreshold permutations like 0.00, 0.000000001, etc. and the tests still pass.

I'm guessing this difference is too small of a percentage for resemble.js, fractions of a percent. In which case this is not a Backstop issue, and likely resemble.js. But I thought I'd start here in case we're missing something.

### PR DESCRIPTION
**Pull request by PhilippMi**
instead of the rounded misMatchPercentage string value as suggested in #477

fixes #477 and #528

### CODE REVIEW

**Comment by garris** [comment]
Will this break existing implementations?

**Comment by PhilippMi** [comment]
This change makes backstop more sensitive, so tests which previously passed could fail afterwards (if `misMatchThreshold` is below 0.01).

**Comment by garris** [comment]
@PhilippMi -- If this is the case, I think we need to put this behind a config flag so we don't get a thousand engineers posting about BackstopJS behaving unexpectedly.

Would you be willing to add a flag to the config?  I guess it would be something like `useRawMisMatchValue`?

**Comment by PhilippMi** [comment]
Good idea! I'll change it.

**Comment by PhilippMi** [comment]
@garris Do you still need something?

**Comment by garris** [comment]
Sorry - I didn't see this update.  Looks good!

**Pull request merged**
