### PR TITLE
On ready script for scenarios - feature #102

### PR DESCRIPTION
**Pull request by sanchothefat**
Hi @garris - this a first pass at #102. Works pretty well so far, I just have a simple test where I click a menu toggle in a custom file like so:

```js
module.exports = function( casper, scenario ) {
	casper.click( '.menu-toggle' );
};
```

It'll take an array of scripts as I thought it'd be handy to have a common library eg. for logging in etc... There's also a config option for setting the base path to the scripts so they can be included shorthand.

While I'm not 100% certain on the way to spawn a child scenario re #94 I've written it so that the array of scripts can have custom built in casperjs scripts added to it early in the scenarios loop.

Let me know what you think so far. Not sure I needed to modify the `paths.js` file to be honest, I haven't really tested without a custom config file yet.

### CODE REVIEW

**Comment by garris** [comment]
@sanchothefat  Beautiful!  Very well done -- thank you.  I haven't had a chance to run the code yet but it looks solid.  I will make some minor tweaks and feature this in the next release. It could take a week or so.  Have you attempted to use this for log-in anywhere?  I think that will be a popular use-case.

**Comment by sanchothefat** [comment]
@garris cool, yeah I thought you'd want to make some version number tweaks etc. I haven't tried using it to log in yet but having it running against a local WP site. I'll try it out.

**Comment by jkopcsek** [comment]
Hi! 
Thanks dudes for this great and simple regression testing suite. I really like this new feature, but i wonder: is it possible to wait for some time before returning and making the screenshot? There's no callback in the onReadyScript-function, so casper.wait isn't very useful. Or am I missing something?

**Comment by sanchothefat** [comment]
@jkopcsek in my tests `casper.wait()` does indeed work within the external casper script so you should be able to pretty much any additional casper code you want before it continues to the screenshot stage.

**Comment by jkopcsek** [comment]
Thanks a lot. Looking forward to build some more sophisticated tests!

**Pull request merged**
