### PR TITLE
WIP : Move Gulp tasks to custom CLI #164

### PR DESCRIPTION
**Pull request by JulienPradet**
Hi!

That's still very early in development but that's what I suggest for #164. If it it does not suit the vision, feel free to tell me.

Basically, I've made :

* the CLI folder that does the basic mapping from CLI to the commands.
* the core command system that registers each available command and execute it.
  One can execute a command directly from the javascript file by doing :
```js
var executeCommand = require('backstopjs/core/command');
executeCommand('commandName', 'arg1', 'arg2')
```

In order to ease the transition, I still use the gulp piping system. Its named `vinyl-fs`.
I can dumbly copy/paste the gulp tasks to make them work. Did you have some other refactoring in mind ?

I was also wondering what was the purpose of the _init_.js task ? Is it a task that is always performed on any task ?

Oh, and finally : which version of node are you supporting ?

### CODE REVIEW

**Comment by JulienPradet** [comment]
Ok, so I've updated it with the Promise system.

I've assumed that it would be better to have before (or after) scripts to run concurrently.  (cf. 117f513)

The reason I often start the Promises with
```js
Promise.resolve()
  .then(/*actual work here*/)
```

is because it allows the execute command to be synchrone and to not care about the Promise system at all.

I guess I can now start to do the main refactoring and move parts one by one.

**Comment by garris** [comment]
This is outstanding work.  Please carry on!

I've pushed a new branch -- this one is for you...
https://github.com/garris/BackstopJS/tree/version_2_0

**Comment by JulienPradet** [comment]
Thanks, I will!
This week end, my brother is getting married so it's a bit tough to find some time to work on it ^^ But I'll find some time next week.

**Comment by JulienPradet** [comment]
Just to keep some updates here, I have done some refactoring in order to promisify every tasks. However 0 tests are run now 😂 (but that's a clean way to keep them all green !)

Anyhow, I should push the updates with actual code tomorrow.

**Comment by JulienPradet** [comment]
Ok so the basics seems to be working right now.

I still need to make a pass and read every details I've done since I had a few problems and things didn't go as smoothly as before.

Once it's done, I'll need some help to identify features that I didn't forgot. I'll also try to add some automated testing in order to ease future refactoring.

Does it seem good to you ? @garris / @levithomason

**Comment by garris** [comment]
Hi,  was reviewing early this morning but didn't get a chance to finish -- but looked pretty good in general!   Great work!   

Please change the PR to the version 2 branch when you get a chance.   I'll pull that in so we can start hitting the actual code.

**Comment by levithomason** [comment]
High level scan looks good to me.  I'll test this out more in depth soon as I can and offer more insightful feedback.

Not sure your preference @garris, but I'd like to have used [`yargs`](https://github.com/yargs/yargs) and [`liftoff`](https://github.com/js-cli/js-liftoff) for the CLI.  These two packages make for very robust CLIs in regard to arg parsing, help, and config file naming, syntax, and pre-compiling.

**Comment by levithomason** [comment]
You can an example implementation of Liftoff in the gulp-cli [here](https://github.com/gulpjs/gulp-cli/blob/master/index.js#L32).

**Comment by JulienPradet** [comment]
For the branch, is there any way to change this PR, or do I have to create a new one ?

**Comment by levithomason** [comment]
Man, I wish :/

https://github.com/isaacs/github/issues/18

**Comment by garris** [comment]
Merged to `version_2_0`!   I will try to review the commits on my way home today.  Thank you!

**Comment by garris** [comment]
@julienPradet  just wanted to let you know, the PR is great -- there are already new PR's against it.  See branch `2_0_onigotez`

**Comment by JulienPradet** [comment]
Alright! Thanks for letting me know. I'll look at what are the differencies for keeping myself up to date.

Do you have any plans for what's needed before launching 2.0 ? How can I help ?

**Comment by garris** [comment]
@JulienPradet  I think the most recent contributions are incredible and I'd like to release as soon as everyone has their fixes in and the docs are accurate.  

I am also considering changing the name to BackstopCLI.   thoughts anyone?

Also I think the web page backstopjs.com branding is lacking.   I'd like to do add real screen shots (maybe video) and also I'd really really like a mascot or logo.   EmberJS is a good example of an open sourced framework with a great branding mascot.  I really think Backstop needs something like that!

**Pull request closed without merging**
