### PR TITLE
Pin client to specific Docker image version

### LINKED ISSUE #861: Updates to backstopjs/backstopjs Docker image break old versions of backstopjs client
It seems like a new version of the backstopjs/backstopjs Docker image was published. Unfortunately, that will cause old versions of the backstop CLI to use this newer Docker images: https://github.com/garris/BackstopJS/blob/master/core/util/runDocker.js#L20

This can cause issues when copying code into the Docker images:
```
Status: Downloaded newer image for backstopjs/backstopjs:latest
/usr/local/lib/node_modules/backstopjs/core/command/remote.js:13
    for await (const data of child.stdout) {
        ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at requireCommand (/usr/local/lib/node_modules/backstopjs/core/command/index.js:44:26)
```

Ideally, each version of backstopjs CLI should use a corresponding version of the backstopjs Docker image. For example, 3.6.0 can use `backstopjs/backstopjs:3.6.0` docker image.

### PR DESCRIPTION
**Pull request by gabegorelick**
This way new Docker images won't break existing clients.

Closes #861

### CODE REVIEW

**Comment by garris** [comment]
Thanks for this!

**Comment by garris** [comment]
Do you prefer that I push a release before merging?

**Comment by gabegorelick** [comment]
> Do you prefer that I push a release before merging?

@garris Yes, if you could cut a new release that would be helpful.

Thanks.

**Comment by garris** [comment]
Will do.  Thanks.

**Comment by garris** [comment]
Done!  Thanks for catching this issue and for submitting the PR.

Please validate backstopjs@3.5.16 when you get a chance.

Cheers.

**Pull request merged**
