### PR TITLE
Removing Casper and Chromy

### PR DESCRIPTION
**Pull request by brendonbarreto**
WIP

closes https://github.com/garris/BackstopJS/issues/879

### CODE REVIEW

**Comment by brendonbarreto** [comment]
@garris Will we continue with this configuration of engine_scripts? For me it makes sense to remove, because after this PR we will only have the Puppeteer available.

**Comment by brendonbarreto** [comment]
Only now that I realized that on issue you did not mention chromy. Are we going to stay with chromy support?

**Comment by brendonbarreto** [comment]
Creating a more e

**Comment by garris** [comment]
We will keep engine scripts because we will likely add new engines at some point -- e.g. maybe selenium driver.

**Pull request closed without merging**
