### PR TITLE
Update to latest node LTS: 16.14.0

### PR DESCRIPTION
**Pull request by anthony-hull**
I built this locally and my project's tests still run using the built image after the upgrade.
Is there any other testing you would want doing on this?

It does include an upgrade to a new version of Debian as the node 16 image uses a new major release .

### CODE REVIEW

**Comment by garris** [comment]
Thank you!

**Comment by fuhlig** [comment]
Additionally to the node update there was this change:
https://github.com/anthony-hull/BackstopJS/blob/1dea8826051fc0254ce75d3c8039f321dd90dda7/docker/Dockerfile#L32

Could you please add details what / why this change was made? Was not able to retrace it in the commit
Thanks in advance :)

**Comment by anthony-hull** [comment]
The upgrade to Debian Buster via moving to the new node image has this missing as a dependancy for puppeteer.
Once I added this it worked again.

**Comment by fuhlig** [comment]
Thanks for clarifying 👍

**Pull request merged**
