### PR TITLE
Scenario Specific Viewports

### PR DESCRIPTION
**Pull request by SengitU**
This PR will provide scenario specific viewports. Previously, tests were executing accordingly to viewports provided by configuration. With this PR, global viewports will be able to overrided by the scenario specific ones.

For more information see #472

### CODE REVIEW

**Comment by garris** [comment]
Thanks for this PR!   I don't have enough time to publish this today but this will definitely go out in the next release.

**Comment by garris** [comment]
Pushed to NPM.  V3.5.8

**Comment by SengitU** [comment]
@garris Hello, thanks for merging and releasing this so fast!

**Comment by garris** [comment]
🤔 

Ok,  I’ll try to check this today.

**Comment by garris** [comment]
Ok, apologies. My bad. Please validate using v3.5.9.  Thanks!

**Pull request merged**
