### PR TITLE
411 compare file hashes

### PR DESCRIPTION
**Pull request by klausbayrhammer**
Tests with `npm run integration-test` for the compare-step

Before (compare images with node-resemble):
2422ms

After (comparing images based on md5sum):
27ms

### CODE REVIEW

**Comment by skip405** [comment]
That's a cool thing :)

**Comment by garris** [comment]
I am so sorry for not getting through this yet.   It really looks good.   Should we try merging it to the canary branch?

**Comment by klausbayrhammer** [comment]
Np, we're using my branch in our CI-System for the last week and it worked miracles for us.

**Comment by garris** [comment]
I'll have some time to merge this tomorrow.  Thanks!

**Comment by garris** [comment]
Ok man -- it's in!   There was another feature that went in today so I merged this one in by hand.  

Please let me know if it works!   And apologies in advance if I screwed anything up in the manual merge.   This is awesome.   Cheers.

`npm install backstopjs@canary -g`

**Pull request closed without merging**
