### PR TITLE
workaround incomplete screenshots for large pages by introducing a new (opt-in) config option

### PR DESCRIPTION
**Pull request by sballesteros**
See https://github.com/GoogleChrome/puppeteer/issues/477 
This was inspired by the discussion in https://github.com/garris/BackstopJS/issues/820

### CODE REVIEW

**Comment by juliquiron** [comment]
I applied this patch in my work environment and I confirm that it is working fine. 

Thanks @sballesteros for your work here!

**Comment by garris** [comment]
Thanks for this @sballesteros and for checking @juliquiron.   I do not have the bandwidth to merge this now -- but will queue this up.   As long as the new dependency does not raise any security issues this will eventually be merged.  Best, GS

**Comment by An-dy1** [comment]
> As long as the new dependency does not raise any security issues this will eventually be merged. Best, GS

Sweet! I've also been running into this problem.

**Comment by An-dy1** [comment]
It would be awesome to see this fix merged

**Comment by Its-Alex** [comment]
@garris Up ?

**Comment by garris** [comment]
This was manually applied here... https://github.com/garris/BackstopJS/commit/273a9ad74f5b76edaff0944fe8f07216bcab0172

Please note change with `mergeImgHack` flag -- changed to binary switch.  Seems we could fall back to viewport height setting for this?  

```
add mergeImgHack by @sballesteros 

added config option `config.mergeImgHack `

Setting this to true uses merge-img lib to stitch multiple images together instead of taking one large image via puppeteer.

The screenshot height is set at the top of runPuppet.js with `const MERGE_IMG_SEGMENT_HEIGHT = 2000;`

I would prefer this value to be set by the current viewport height set in the config.   (If I am understaning this feature correctly.)

This fixes issue experienced with very large page heights.

Needed to merge this manually because of rebase issue.
```

Install with `npm install backstopjs@beta`

Please validate and provide feedback -- should this become the primary full screen path?

**Comment by smokris** [comment]
(The `mergeImgHack` option was removed in 1c549682c7c9d73bc6e2cb0bde26f96988c5a0da.)

**Pull request closed without merging**
