### PR TITLE
Accept chromePath in config file

### PR DESCRIPTION
**Pull request by kiran-redhat**
chrome's executable location can be specified with 'chromePath' property in BackstopJS config file.

### CODE REVIEW

**Comment by garris** [comment]
Can we make a change?  How about changing `hostFlags` to `hostConfig`, then directly extend the chromy options object.   We should also make `hostFlags` backward compatible and have it extend `chromeFlags` if specified separately.   I think this keeps the api footprint small and flexible as new requirements are added.   What do you think?

**Comment by kiran-redhat** [comment]
Sounds good..I will work on that..

**Comment by kiran-redhat** [comment]
is this what you mean @garris ?

**Comment by kiran-redhat** [comment]
Hey @garris, I've tested, this accepts chromePath, hostFlags and newly added engineConfig(happy to change it to hostConfig). I am happy to add engineConfig for Casper as well, your thoughts ?

**Comment by garris** [comment]
@kiran-redhat  I'm sorry.   I didn't see your update!   I just pushed a commit that might clobber some of your changes.

I have some feedback on your PR.   I will follow up as soon as I can.  Thanks so much.

**Comment by garris** [comment]
@kiran-redhat  here is a more detailed acceptance criteria.  Sorry for not being clearer before.   Hope this helps.


Behavior 
----

The engineConfig property will accept an object and be used as the chromy options argument.  (Line 164)

If no engineConfig property is set then a default configuration will be used.  

If engineConfig is provided then all property values supplied will be appended, or override, any default chromy option values that would otherwise be used.   The one exception to this is the chromeFlags property.

The chromeFlags property, will always be overwritten by the internally generated `flags` variable (see line 159).  However, engineConfig.chromeFlags will override engineFlags is both are present.   engineFlags should still work for backward compatibility.   If found -- please add a console log warning users that engineFlags is deprecated. 

the debugWindow flag should behave the same way as chromeFlags.  It will not be depricated. 

Implementation 
----
Create an internal default property and use object.assign() to extend the property-- which will be used as an input to new Chromy().

**Comment by garris** [comment]
And thank you adding the extra flags -- I have added the ability to directly set any properties in chromy with an `engineOptions` property -- so now all options are available.

Please see and comment on https://github.com/garris/BackstopJS/pull/569/files#diff-04c6e90faac2675aa89e2176d2eec7d8

thank you!

**Comment by kiran-redhat** [comment]
@garris , I think this looks good, I will test and let you know.

**Comment by kiran-redhat** [comment]
This change is been done and merged to master from https://github.com/garris/BackstopJS/pull/569, so closing this.

**Pull request closed without merging**
