### PR TITLE
Docker command template

### LINKED ISSUE #967: Docker - the input device is not a TTY
I'm trying to run my tests on a TFS build. However, I got the following error:

`the input device is not a TTY`

I know that this is related to `-it` flag on `docker run` command, but I'm afraid that i cannot remove this flag without submitting a PR (I dont know why backstop uses `-it` also) and I cannot activate tty on the server in which TFS is running.

Any ideas about that?

### PR DESCRIPTION
**Pull request by gyanta**
Fixes #967

### CODE REVIEW

**Comment by screendriver** [comment]
@garris you put the new behaviour to the [README](https://github.com/garris/BackstopJS#using-docker-for-testing-across-different-environments) of the repo but not releasing it? 😉 Could lead to some issues where people complain because something is not working 😁 

Or in short: could you release that please? ☺️

**Comment by garris** [comment]
Ah, yes, great point.   So,  just tried to publish to npm -- but I'm getting a "can't parse json" exception. 🤔

Will try again later tonight.   Sorry.

**Comment by garris** [comment]
Ok.  Tis published!
`npm install -g backstopjs@canary`

If someone can validate canary I'll go ahead and publish to latest.

**Comment by garris** [comment]
Ok. now looks like docker build in failing with...
```
Status: Downloaded newer image for node:8.12.0
---> ce426dead114
Step 2/12 : ARG BACKSTOPJS_VERSION
---> Running in 4e97b19e29c9
Removing intermediate container 4e97b19e29c9
---> df45840ef295
Step 3/12 : ENV BACKSTOPJS_VERSION=$BACKSTOPJS_VERSION NPM_CONFIG_UNSAFE_PERM=true
---> Running in 1d42b437584c
Removing intermediate container 1d42b437584c
---> e9df36ddbf1d
Step 4/12 : RUN apt-get update && apt-get install -y git sudo software-properties-common python-software-properties
---> Running in 434d1fe3ead6
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:3 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Err http://deb.debian.org jessie-updates/main amd64 Packages
Err http://deb.debian.org jessie-updates/main amd64 Packages
Err http://deb.debian.org jessie-updates/main amd64 Packages
Err http://deb.debian.org jessie-updates/main amd64 Packages
Err http://deb.debian.org jessie-updates/main amd64 Packages
404 Not Found
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [822 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages 404 Not Found
```

Will see if bumping node fixes this tomorrow.

**Comment by screendriver** [comment]
I can't test all of this because `Unable to find image 'backstopjs/backstopjs:3.9.9'`

@garris did you forget to deploy something to Docker Hub? 😉

**Comment by garris** [comment]
@screendriver  Yup.  Welcome to my world.   I tried a few times to address the docker issue by simply removing dependencies.  3.9.10 is building now.  I don't expect it to work.  But it might.   

*Any help would be mucho appreciated!*

**Comment by garris** [comment]
Just tried bumping node image.

**Comment by garris** [comment]
OK GOT IT.   v3.9.13 is building now.

**Comment by screendriver** [comment]
Tried `4.0.1` and get

```sh
BackstopJS v4.0.1
Loading config:  /src/backstop.json 

COMMAND | Executing core for "test"
createBitmaps | Selected 1 of 1 scenarios.
      COMMAND | Command "test" ended with an error after [0.043s]
      COMMAND | Error: Failed to launch chrome!
                /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
                
                
                TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
                
                    at onClose (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/Launcher.js:342:14)
                    at Interface.helper.addEventListener (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/Launcher.js:331:50)
                    at Interface.emit (events.js:194:15)
                    at Interface.close (readline.js:379:8)
                    at Socket.onend (readline.js:157:10)
                    at Socket.emit (events.js:194:15)
                    at endReadableNT (_stream_readable.js:1125:12)
                    at process._tickCallback (internal/process/next_tick.js:63:19)
COMMAND | Executing core for "openReport"
openReport | Attempting to ping 
   COMMAND | Command "test" ended with an error after [85.712s]
   COMMAND | Error: docker run --rm -it --mount type=bind,source="/Users/me/project",target=/src backstopjs/backstopjs:4.0.1 test "--moby=true" returned 1
                 at ChildProcess.<anonymous> (/Users/me/project/node_modules/backstopjs/core/util/runDocker.js:50:18)
                 at ChildProcess.emit (events.js:189:13)
                 at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Error: docker run --rm -it --mount type=bind,source="/Users/me/project",target=/src backstopjs/backstopjs:4.0.1 test "--moby=true" returned 1
    at ChildProcess.<anonymous> (/Users/me/project/node_modules/backstopjs/core/util/runDocker.js:50:18)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
error Command failed with exit code 1.
```

**Comment by garris** [comment]
Yup.  This is a different problem.   Dependency issue with chrome.   working on it.

**Comment by garris** [comment]
Issue seems to be this...
`error while loading shared libraries: libX11-xcb.so.1 `

Just pushed out v4.0.3 -- put the chrome deps back in.   If that doesn't work we can look at what these guys are talking about...  https://github.com/Googlechrome/puppeteer/issues/290#issuecomment-322836830

**Comment by garris** [comment]
Ok.  4.0.3 works over here!   Thanks for hanging in!   Please let me know if you see any issues on your end.  Cheers!

**Comment by screendriver** [comment]
Cool! 😎 🙌 🎉

**Pull request merged**
