### PR TITLE
xunit testcase addition even for successcase

### PR DESCRIPTION
**Pull request by nobso**
It is useful to see all the test-cases all the time irrespective of success/failure.

### CODE REVIEW

**Comment by nobso** [comment]
@garris can you please review this?

**Comment by nobso** [comment]
@garris sorry to bother you, it would be great if it gets merged soon :) my build is broken and waiting for this fix

**Comment by garris** [comment]
Done.

**Comment by nobso** [comment]
@garris Thank you! can you please update the npm package as well?

**Comment by garris** [comment]
Done.  Sorry for the delay -- I didn't have my computer with me.  Thanks so much for taking care of the bugs.

**Comment by nobso** [comment]
Its my pleasure!  Yes, i see the upgraded version now, thanks.

**Pull request merged**
