### PR TITLE
#127 global config for misMatchThreshold/readyEvent

### PR DESCRIPTION
**Pull request by klausbayrhammer**
adds the ability to specify global configs for mismatchThreshold and readyEvent. Both configs can be overridden by specifying either readyEvent or mismatchThreshold on a scenario level

### CODE REVIEW

**Comment by garris** [comment]
I think we still need to add lines here-ish...
https://github.com/garris/BackstopJS/blob/master/gulp/util/paths.js#L71

adding...
```
paths.misMatchThreshold = config.misMatchThreshold || null;
paths.readyEvent = config.readyEvent || null;
```

**Comment by garris** [comment]
Merged.  I added the paths parameters -- so I expect this to work.  Please test.  Thanks!

**Comment by klausbayrhammer** [comment]
Thanks for merging. I tested it without adding the two properties to paths and it worked quite fine. `genBitmaps.js` just reads the `capture/config.json` which is a copy of the current backstop config - or am I missing something?

**Comment by garris** [comment]
You are correct.   I removed the lines.   Thanks!

**Comment by klausbayrhammer** [comment]
Is there a chance that you could release the last couple of changes in a version 1.0.1?

**Comment by garris** [comment]
Done!

**Comment by klausbayrhammer** [comment]
Awesome! Thanks!

**Pull request merged**
