### PR TITLE
CLI Authentification

### PR DESCRIPTION
**Pull request by svwu**
Hello @garris 
This is my requested change for authentication via CLI.
It's npm conform and gives the optional parameters --user="" and --password=""

So in an automated flow we can auth several users via CLI.

Best,
Sven

### CODE REVIEW

**Comment by svwu** [comment]
Hello @garris,
Can you please have a short review?
Thanks!

**Comment by svwu** [comment]
Hello @garris,
it's my third time now, to get a response, can you please review or give your thoughts about my PR?
Thanks!

**Comment by svwu** [comment]
Hello @garris ,
we really strongly do need this authentification for our development, as we aim for tests on different servers with different authentifications.

Can you please find some minutes to review?

Thanks!

**Comment by garris** [comment]
Thank you @svwu.  Apologies for the delay.   Will try to push this to NPN today.  Best,  Garris

**Comment by garris** [comment]
@svwu this is now at `npm install -g backstopjs@beta`  Please verify when you get a chance.  Thanks for your patience.  Garris

**Comment by svwu** [comment]
Hello @garris ,
I had to do a change, because of the usage of the backstop command instead of npm run [task]

My Pull Request can be found at: https://github.com/garris/BackstopJS/pull/373

Best,
Sven

**Pull request merged**
