### PR TITLE
Playwright engine

### LINKED ISSUE #1142: Are there plans to support playwright
I recently learned about https://github.com/microsoft/playwright which is a project by former puppeteer developers but now working for microsoft instead of goodle and now supporting multiple engines ( Chromium, WebKit and Firefox) wwith a single API. 

Being able to check for Chrome and Firefox would be such a great feature in my opinion.
The API should be similar to puppeteer which is currently implemented.

Any thoughts?

### PR DESCRIPTION
**Pull request by FrostyShosty**
This adds Playwright as an alternative engine to Puppeteer.  The readme has been updated with the configuration changes needed to switch to Playwright, as well as a discussion of the additional engineOption "browser", to specify which playwright browser to use.

All advanced scenario options have been tested and seem to work well, including hide/removeSelectors, keyPressSelectors, specific selectors for screenshots, etc.  In addition, the default onBefore/onReady scripts have all been updated, including CSS overriding, intercepting images, and loading cookies.

The only untested features were Docker integration and the ignoreCSP script.

Fixes #1142

### CODE REVIEW

**Comment by garris** [comment]
Wow.  Early Christmas gift!  🎅 

Thanks so much for this contribution -- going through this now.

**Comment by garris** [comment]
LGTM!   Will merge this and test locally.

Just a question -- your github account looks brand new -- yet your work looks like you have a lot of experience.   So I gotta ask -- what is up with that?  🙂

**Comment by garris** [comment]
published


```
npm notice === Tarball Details ===
npm notice name:          backstopjs
npm notice version:       6.0.1
npm notice package size:  22.8 MB
npm notice unpacked size: 28.2 MB
npm notice shasum:        891082b586ede1b266c75a59387678eb30e350db
npm notice integrity:     sha512-6BJ6I6pJtndN3[...]cTumSweLV54qA==
npm notice total files:   534
npm notice
+ backstopjs@6.0.1
```

**Comment by FrostyShosty** [comment]
Thanks for the merge, @garris!  I've been doing software dev. for a long time, but its been primarily in the commercial sector, so I haven't had much chance to contribute back to the community.  Really glad to be able to help out here!

I did see you reported that keyPressSelector wasn't working for you - this seems working for me, can you give any more details about the failure?

**Comment by vsshk** [comment]
@FrostyShosty can this casing that issue:

**Comment by garris** [comment]
@FrostyShosty 
> I did see you reported that keyPressSelector wasn't working for you - this seems working for me, can you give any more details about the failure?

Thanks for checking on this!   This was the only test that I saw an issue on. Left side is puppeteer/chrome,  right side is playwright/chromium.   Looks like the keyed text didn't work...

image

The test lives here...
`test/configs/backstop_features.js`

**Comment by garris** [comment]
@FrostyShosty   also, looks like @vsshk might have found and issue up there in the post before mine 👆 

Thanks!

**Comment by FrostyShosty** [comment]
@vsshk Thanks for the report!  Looks like I may have been overzealous in my javascript.  The ?? "Nullish coalescing operator" is fairly widely supported, but I guess not fully covering the Backstop userbase.  I'll get a PR going to simplify that.

**Comment by FrostyShosty** [comment]
PR #1379 is now available.  I didn't realize the smoke test both had its own engine config, and used its own set of scripts.  I've brought in the Playwright scripts, and all tests seem to pass.  I also updated the reference images from a fresh docker run.  Please let me know if anybody runs into anything else!

**Comment by karpstrucking** [comment]
Just wanted to thank you all for this enhancement. We've been smashing our heads against Puppeteers inability to make good screenshots when elements use `vh` units in height declarations and switching to Playwright/Firefox is working quite well!

**Pull request merged**
