### PR TITLE
Adds an argument to specify the location of backstop.json

### PR DESCRIPTION
**Pull request by klausbayrhammer**
Refs #87 Adds the ability to pass an `backstopConfigFilePath` argument to backstop tasks which specifies the location of the `backstop.json`

### CODE REVIEW

**Comment by jkopcsek** [comment]
:+1: Looking forward to this!

**Comment by klausbayrhammer** [comment]
Yes everything's finished!

**Comment by garris** [comment]
Fabulous!   Will work on this next week!

**Comment by ay13** [comment]
Hi everyone. Been almost 3 weaks and just wanted to check on progress.

**Comment by garris** [comment]
@ay13 -- so sorry for the delay!  It's really my fault -- @klausbatrhammer put up a beautiful looking PR but I have been mired in a platform migration for my day job.    

Because this is such a high-impact change I really need to be careful. I will merge as soon as I can.   Thank you for your patience.

**Pull request merged**
