### PR TITLE
Generate Junit reports on error

### PR DESCRIPTION
**Pull request by prevostc**
I don't know why but the test condition prevented the report from being generated.

### CODE REVIEW

**Comment by garris** [comment]
@nobso Could you kindly take a look at this PR when you have a moment.  Since this is your feature I would like you to review.   Thank you!

**Comment by nobso** [comment]
@garris sure, i will do it tonight.

**Comment by nobso** [comment]
@prevostc what are the changes you have had? could you please list the steps here?

**Comment by nobso** [comment]
@prevostc can you please provide me the steps to reproduce?

**Comment by prevostc** [comment]
@nobso Sure, but I'm leaving on vacation today, I will provide more details by July, sorry for the delay :s

From what I remembered, the report simply did not get generated with the version I'm using, I only added "CLI" to the report list.
I did not fully understand the code either but I needed a quick fix for a work-related project and this test seemed to block the report generation.
Now that the report is generated on my side, I will have more time to craft you a more detailed scenario, independent from the project that i'm working on.

**Comment by nobso** [comment]
@prevostc Ok, no problem. You may follow these instructions https://github.com/garris/BackstopJS#test-report-integration-with-a-build-system-like-jenkinstravis

**Comment by nobso** [comment]
@prevostc https://github.com/garris/BackstopJS/pull/211 fix might have fixed your issue too. Please check and confirm!

**Comment by prevostc** [comment]
Ok, I'll check that this week, thanks!

**Comment by garris** [comment]
Closed by #259

**Pull request closed without merging**
