### PR TITLE
Engine options update

### PR DESCRIPTION
**Pull request by garris**
Setting an engine parameter value with engineOptions will override any default value set by backstop. 

- (TLDR) Setting `port` is _very_ _very_ not advised.
- Setting `chromeFlags` will override all chromeFlags properties set by backstop -- **EXCEPT FOR `--window-size`***...  (i.e. `--window-size` flag will be added by backstop if not found in chromeFlags) 
- Setting `--window-size` explicitly in `chromeFlags` will override values used in your viewport settings.

### CODE REVIEW

**Comment by VladimirPittner** [comment]
Seems to work now for me. WaitTimeout altered successfully from config.

**Config:**
```
engine: "chrome",
engineOptions: {
    waitTimeout: 120000,
    chromeFlags: ['--disable-gpu', '--force-device-scale-factor=1', '--disable-infobars=true']
},
```
**Console output:**
```
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1024,1000"],"port":9222,"waitTimeout":120000,"visible":true}
```

**Comment by garris** [comment]
Boom!  Nice!  Thanks for your patience.   Will try to merge this today.

**Comment by kiran-redhat** [comment]
@garris , yup, double yes 👍 works fine (I've tested with chromePath in addition) and below is the log:

Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,4600"],"port":9223,"waitTimeout":90000,"visible":false,"chromePath":"path/to/chrome","gotoTimeout":360000}

**Comment by garris** [comment]
Awesome.  Thank you for testing!   I didn’t get to merge it today.  But will do it very soon.

**Comment by VladimirPittner** [comment]
Thanks a lot, got new update works fine :)

**Pull request merged**
