### PR TITLE
Fix start task on windows

### PR DESCRIPTION
**Pull request by YuliaTsareva**
I would suggest it as fix for https://github.com/garris/BackstopJS/issues/59.
Tested on Windows.

### CODE REVIEW

**Comment by garris** [comment]
Hi,  this is merged onto master.   Can you pull this and verify?  Please let me know if it is working on windows.  Also, are you able to test this on OS X?

**Comment by YuliaTsareva** [comment]
Thank you, I will test it on Windows and OS X today at night.

**Comment by YuliaTsareva** [comment]
@garris It works both on OS X and Windows.

**Comment by garris** [comment]
@YuliaTsareva Thanks Yulia!   It will go out in the next release.   Cheers, Garris

**Pull request merged**
