### PR TITLE
Add HTTPS protocol option to CasperJS spawn task.

### PR DESCRIPTION
**Pull request by Chapabu**
Added args array for holding arguments to pass to CasperJS/PhantomJS.
Concatenated tests and args array into a casperArgs array to pass to spawn(casperProcess).

### CODE REVIEW

**Comment by Chapabu** [comment]
This should fix #38. I've added another array so as not to confuse the `tests` array. I've then concatenated this array with the previous tests array.

**Comment by Chapabu** [comment]
See #38

**Comment by garris** [comment]
Super!  Thank you for the pull request.  Will pull later today.  Best GS

**Comment by garris** [comment]
Looks good!    @Chapabu do you have a backstop.json config you used to test this?

**Comment by Chapabu** [comment]
Sure, I've added a gist here: https://gist.github.com/Chapabu/787ddfebd5cf6d751278

I tested against 3 HTTPS pages and 3 non-HTTPS pages to ensure nothing was broken.

**Comment by garris** [comment]
So, here is something interesting.   I used your test file on the previous backstopjs version 0.4.1 and it seems to have rendered everything fine.  See attached.   

Maybe this issue only applies to certain versions of Phantom?   

What version of Phantom are you running?  And what OS?

```
garriss-macbook:backstopjs gshipon$ phantomjs -v
1.9.8
```

screen shot 2015-02-23 at 3 46 23 pm

**Comment by Chapabu** [comment]
I'm running the following:

OSX Yosemite
PhantomJS 1.9.7
CasperJS 1.1.0-beta3

Although I have just noticed that PhantomJS 1.9.8 has changed the default ssl protocol to TSLv1 instead of SSLv3 ([release notes](http://phantomjs.org/release-1.9.html)), so this looks like the main problem was me being on the previous release of PhantomJS. That makes me feel slightly silly as it's the first thing I should have checked!

So yeah, this issue is/was only apparent on PhantomJS < 1.9.8.

**Comment by garris** [comment]
Cool.  Mystery solved!    I am still tempted to keep the change in however -- I don't mind being a little bit more compatible with older versions.   My only concern would be that adding this flag could somehow break the current or future versions of Phantom. 

Or, I can just as easily back out the change.

Any thoughts there?

**Comment by Chapabu** [comment]
I think it's useful for now, as it allows Backstop to work for HTTPS pages in all _available_ versions of PhantomJS. However, I see the concern with potential future breakage. I guess the only real failsafe would be to tweak the `.travis.yml` file and add [matrix variables](http://docs.travis-ci.com/user/environment-variables/#Matrix-Variables) for different versions. So you could explicitly run travis against 1.9.7, 1.9.8, and whichever is the latest version from npm. 

I think it'd probably look a little like this:

``` yaml
language: node_js
node_js:
  - "0.10"
env:
 - PHANTOM_VERSION='1.9.7'
 - PHANTOM_VERSION='1.9.8'
 - PHANTOM_VERSION='latest'
install:
  - npm install gulp -g
  - npm install phantomjs@PHANTOMJS_VERSION -g
  - npm install casperjs -g
  - npm install
script:
  - gulp reference
  - gulp test
```

That way travis would run against the older, `SSLv3` default argument, the newer `TSLv1` default argument, as well as checking it still works against the latest PhantomJS from NPM.

I can try a pull request for this as well if you'd like, but it'd have to wait until tomorrow as it's 12:30am where I am now :sleeping:

**Comment by garris** [comment]
Thanks so much for your input on this thing.   I think that if that flag does not break Phantom 1.9.8 then we can just go forward with that.   I don't think we need to add the travis complexity.   If you get around to verifying with phantom 1.9.8 then that is great.   If not, I will try to get to it in a few days.   Thanks again!

**Pull request merged**
