### PR TITLE
Specify path for the backstop.json config file - feature #87

### PR DESCRIPTION
**Pull request by gregsqueeb**
We are looking to use backstop.js across multiple teams and it would be great to allow each team have their own config file.

Trying to solve this issue:
https://github.com/garris/BackstopJS/issues/87

### CODE REVIEW

**Comment by garris** [comment]
@gregsqueeb Hi, #87 was already merged to master.   Was this not working for you?

**Comment by garris** [comment]
UPDATE:   I just installed from master.  I followed the documentation and #87 worked for me...

> The location of the backstop.json file can be specified by passing a backstopConfigFilePath argument to the backstop tasks. E.g. by passing --backstopConfigFilePath=../../src/test/

So, you should be able to install from master and do...
`npm install garris/backstopjs#master`

`gulp test --backstopConfigFilePath=[PATH TO YOUR FILE]`

**Comment by gregsqueeb** [comment]
Lol, sorry about that! From the readme it looked like that flag only worked when generating a documentation file not all the time! Thanks for the helpful comments and your quick responses! Been loving backstopjs

**Comment by garris** [comment]
I'm glad you filed the bug -- I will update the docs to make it more obvious.   Cheers!

**Pull request closed without merging**
