### PR TITLE
Update README.md for NPM Install

### PR DESCRIPTION
**Pull request by jehoshua02**
+ Changes all usage over bower over to npm.
+ Changes references to `./bower_components` to `./node_modules`.

### CODE REVIEW

**Comment by jehoshua02** [comment]
Related issue: https://github.com/garris/BackstopJS/issues/26

**Comment by garris** [comment]
@jehoshua02 There is [an article here](http://css-tricks.com/automating-css-regression-testing/) which we should really update prior to releasing this change.

**Comment by jehoshua02** [comment]
@garris I'll let you handle that one. But there's nothing else in the repository?

**Comment by garris** [comment]
I don't think so.   Great progress!

**Pull request merged**
