### PR TITLE
Use opn instead of open

### PR DESCRIPTION
**Pull request by ataylorme**
The [open package](https://www.npmjs.com/package/open) has not been updated in 4 years and has a [ciritical security vulnerability](https://nodesecurity.io/advisories/663). This replaces it with the [opn package](https://www.npmjs.com/package/opn) which is well maintained by the great [sindresorhus](https://www.npmjs.com/~sindresorhus) and does not have vulnerabilities.

### CODE REVIEW

**Comment by ataylorme** [comment]
@garris I didn't see a contributor guide or anything so I hope this PR is okay. Let me know if you need more details or would like to chat.

**Comment by garris** [comment]
@ataylorme Oh man -- this looks great.  Thanks for the PR.   Cheers!

**Comment by garris** [comment]
I had to revert this because `opn` was hanging -- see screenshot.   Did this work on your machine?

screen shot 2018-05-18 at 5 48 58 pm

**Comment by ataylorme** [comment]
@garris sorry for the delay. I have been away from the computer for the weekend. `opn` is working fine for me with Backstop on my branch.

backstopjs-opn-test

**Comment by garris** [comment]
Hi there,  thanks for the screencast — but this doesn’t show the CLI issue.  The browser opens for me — but the CLI doesn’t return — it just hangs and needs to be exited manually with ctrl+c.   Can you take a look?

**Pull request merged**
