### PR TITLE
Run contained instance on host network

### PR DESCRIPTION
**Pull request by andyrichardson**
Fix for Linux when `127.0.0.1` connections are refused.

Relating to #845.

### CODE REVIEW

**Comment by garris** [comment]
@andyrichardson Would you mind documenting what this change does & how it works?

-link to docker api doc for this flag
-summarize the change
-what use-cases will this affect?
-do we expect this change have a negative impact on existing implementations?  Please consider for Win/OS X/Linux 

Thanks!

**Comment by andyrichardson** [comment]
Hey @garris, sorry for not checking this earlier.

The justification for using host networking was so that the ports mapped to the host would be accessible to the container at IP `127.0.0.1` (currently, trying to access a host port from the container in Linux is not possible). 

After double checking [the documentation](https://docs.docker.com/network/host/), it looks as though host networking is not supported on macOS/Windows. Whether the addition of this argument will break functionality outside of Linux environments is something I am unsure about. I'll have to experiment more on this but for the time being, I'll close this request.

**Comment by andyrichardson** [comment]
Hey @garris, sorry for not checking this earlier.

The justification for using host networking was so that the ports mapped to the host would be accessible to the container at IP `127.0.0.1` (currently, trying to access a host port from the container in Linux is not possible). 

After double checking [the documentation](https://docs.docker.com/network/host/), it looks as though host networking is not supported on macOS/Windows. Whether the addition of this argument will break functionality outside of Linux environments is something I am unsure about. I'll have to experiment more on this but for the time being, I'll close this request.

**Comment by andyrichardson** [comment]
Hey @garris, sorry for not checking this earlier.

The justification for using host networking was so that the ports mapped to the host would be accessible to the container at IP `127.0.0.1` (currently, trying to access a host port from the container in Linux is not possible). 

After double checking [the documentation](https://docs.docker.com/network/host/), it looks as though host networking is not supported on macOS/Windows. Whether the addition of this argument will break functionality outside of Linux environments is something I am unsure about. I'll have to experiment more on this but for the time being, I'll close this request.

**Pull request closed without merging**
