### PR TITLE
Adding diff button to ScrubberModal component (#710)

### PR DESCRIPTION
**Pull request by mikkelrom**
Hi @garris and @matthiaskomarek.

I have added this diff button as mentioned in #710 and it looks like this:

image

This is my first time touching a React project, so please bear with me if I missing something 🙂

I would like to get your feedback on it all, but also wether the -1 position makes sense or not for the diff button - suggestions are very welcome!

Thanks!

### CODE REVIEW

**Comment by garris** [comment]
Wow — super exciting— I have wanted to see this feature for a long time!

I will review as soon as I can — but please bear with me — I am preparing to go on holiday EOW.

**Comment by garris** [comment]
I will test this before publishing to NPM.  Will update this PR when pushed to NPM.  Thanks!

**Comment by garris** [comment]
ok -- published to backstop@beta!

install here...
`npm install -g backstopjs@beta`

**Comment by mikkelrom** [comment]
Thanks! Just tested the beta, and it seems to work 👍

**Pull request merged**
