### PR TITLE
Let's spoof user agent

### PR DESCRIPTION
**Pull request by f4bien**
A simple way to override user agent by viewport declaration

### CODE REVIEW

**Comment by garris** [comment]
Hi @f4bien,  sorry for the delay following up on this -- hella busy...   This change looks good.  Can you post a config example to test this with?  Thanks.

**Comment by f4bien** [comment]
No trouble @garris! You can test with this kind of config:

```json
{
  "viewports": [
    {
      "name": "Apple iPhone 6 Plus",
      "width": 414,
      "height": 736,
      "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4"
    }
  ]
}
```

**Comment by garris** [comment]
This looks good.  This viewport node needs to be added to the config file in the `./test/` directory -- and `simple.html` should be updated to display the value onscreen for positive verification.   I will try to do that this week.  You are more than welcome to add it yourself if you can -- it would be a big help.  Either way, thank you.

**Comment by garris** [comment]
Hi @f4bien,  there was a problem with this.   With multiple viewports, setting userAgent on one viewport has the unexpected effect of setting all subsequent viewport settings.  Therefore I am rolling this back.   This would be improved by only effecting the current viewport or by moving that config parameter to the root node of the config file.  Either would be fine for me if you can implement it.  Please let me know how you want to handle it.

thanks!  GS

**Comment by garris** [comment]
````
{
    "viewports" : [
        {
            "name": "phone",
            "width": 320,
            "height": 480
        },
        {
            "name": "Apple iPhone 6 Plus",
            "width": 414,
            "height": 736,
            "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4"
        },
        {
            "name": "tablet_v",
            "width": 568,
            "height": 1024,
            "userAgent":""
        },
        {
            "name": "tablet_h",
            "width": 1024,
            "height": 768
        }
    ],
    "scenarios" : [
        {
            "testName":"simple",
            "url":"test/simple.html",
            "hideSelectors": [
            ],
            "removeSelectors": [
            ],
            "selectors":[
                "body"
            ],
            "readyEvent":"backstop.ready",
            "delay":0
        }
    ]
}
![screen shot 2015-03-13 at 10 05 18 am](https://cloud.githubusercontent.com/assets/447033/6643506/eb857fa0-c969-11e4-9060-2a9cdc0786d5.png)



````

**Pull request merged**
