### PR TITLE
Check comparison image exists before running comparison

### PR DESCRIPTION
**Pull request by limptwiglet**

### CODE REVIEW

**Comment by axe312ger** [comment]
:+1:

**Comment by garris** [comment]
@limptwiglet   Thanks for this.  I will test this tomorrow.  Regards.

**Comment by limptwiglet** [comment]
I added a selector ".missing-selector" to the test/backstop.json file but this threw a casper error and stopped the gulp task continuing. Using this in my project the error failed silently.

**Comment by garris** [comment]
Gulp hangs when I run `gulp reference` and add a missing selector on your branch.  What use case are you working towards?

**Comment by garris** [comment]
Ok. I got it.  Update forthcoming.

**Comment by limptwiglet** [comment]
No worries! Thanks for the project its proving to be very useful.
Expect more contributions from me soon.

**Comment by axe312ger** [comment]
:+1: :+1: :+1:

**Pull request merged**
