### PR TITLE
Changed CLI Auth from npm env to config

### PR DESCRIPTION
**Pull request by svwu**
Hello @garris ,
thanks for your commit to beta!
I tried it and I didn't had in mind that when we use backstop test instead of npm run test, we can't access to npm_env_ vars. 

I updated the access to the args, via the config, because it's allready been used, it's clearer and better and it works with the backstop command.

Best,
Sven

### CODE REVIEW

**Comment by garris** [comment]
Please rebase.

**Comment by svwu** [comment]
There is nothing to rebranch as I forked and checked out vanilla.

**Comment by svwu** [comment]
I rebased my old fork. and solved all conflicts.

**Comment by garris** [comment]
Pushed to NPM!

**Comment by svwu** [comment]
I don't get a new version via npm install / update :/

**Comment by garris** [comment]
@svwu I just wanted to make sure you were able to validate your change in NPM?  Thanks.

**Comment by svwu** [comment]
Hello @garris ,
Yes, it works great now! 
Somehow I won't get the update on backstop@beta, I had to install backstop@2.3.7.
But it works! :)
Thank you!

**Comment by garris** [comment]
Great!  Yes, I skipped @beta because in this case I was vert certain that it worked.  Cheers!

**Pull request merged**
