### PR TITLE
Add online course on tutorial section

### PR DESCRIPTION
**Pull request by wlsf82**
I've been teaching about test automation on Udemy, and I thought it would be nice to list my course about visual regression testing with BackstopJS in the tutorials section of the tool's doc.

@garris, would you mind reviewing it, please?

### CODE REVIEW

**Comment by wlsf82** [comment]
Hey, @garris, do you mind reviewing this PR, please?

**Comment by garris** [comment]
Hey @wlsf82!   I am so sorry -- I thought I had done this already!   Thank you for the reminder!

**Comment by wlsf82** [comment]
No worries, thank you!

**Comment by garris** [comment]
I just added that link to the news section at the top also.  Cheers!

**Pull request merged**
