### PR TITLE
Promote test image as new reference image

### LINKED ISSUE #95: add button to “promote” any selector test
Add the ability to “promote” any _test_ screen capture, e.g. add a "promote” button to each test screenshot on the report -- clicking the button promotes the selected changes to a reference image. 

Reference files would then be updated on a selector by selector basis (without having to run an entirely new reference pass).

### PR DESCRIPTION
**Pull request by ahoopen**
Hi,

I made a pull request that fixes #95. A short summary of what is included in this pull request. 

## **Report**
- Added 'set as new reference' button
- Replace reference file with test file
- Starts a temporary server to handle the replace action
- Automatically close the server when user closes the report tab/window
- Added Update report command

## **Improvements**
- Refactored report command
- Added report helper class
- Added generic utils class  (toAbsolute, ... )

### CODE REVIEW

**Comment by garris** [comment]
@ahoopen this looks great at first glance -- thank you very much for this important feature contribution!   This is a pretty big review so I will need a little time.   Will get back to you as soon as I can.  Cheers!

**Comment by ahoopen** [comment]
@garris No problem! Take your time

**Comment by garris** [comment]
@ahoopen thank you for your patience!  2.0 is finally in soft release mode and I can finally start devoting energy to new PRs.   Unfortunately my projects at work have been freely ramped up so it could still be a few more weeks before I can do a proper review.  But it will happen!   Please know that I really appreciate your effort and will follow up as soon as I can.   Best regards,  Garris

**Comment by garris** [comment]
The feature was added to the cli.  (We ended up not going forward with this GUI PR)

`backstop approve` will promote the latest test run screenshots to reference.  You can add `--filter=<scenarioId>` to approve specific images (this is a regex string against filenames so it's very flexible)

**Comment by mikkelrom** [comment]
@garris Jep, I'm aware of that feature (which is awesome by the way!). 🙂 
Thanks for the info, good to know it just wasn't me 😀

**Pull request closed without merging**
