### PR TITLE
Travis CI config

### PR DESCRIPTION
**Pull request by lewisnyman**
This is some very basic Travis CI config that makes sure the code runs without any hard errors.

Not bullet proof but it's something to build on.

You can see the builds from my repo here: https://travis-ci.org/lewisnyman/BackstopJS

### CODE REVIEW

**Comment by garris** [comment]
Hi Lewis, this is great work.   I see on Line 273 & line 309 of the Travis log that there is an error reported by BackstopJS.  That error is thrown when backstopjs first runs and finds missing dependencies (this is after backstopjs attempts to spawn a bower process to install dependencies for the reporting module).   I think this is easily fixable by simply adding those dependencies to the build repo instead of omitting them like they are now.   

In any case this Travis stuff is useful and I will merge that in.   Would love to clean up this install.   @jehoshua02 suggested some nice improvements in #23 -- How do those look to you?

**Comment by lewisnyman** [comment]
Yes, it would be great if the only command users had to run was npm install. I'd rather stick with the Travis config that maintains the status quo, and then make changes that affect everyone in dedicated issues. How does that sound?

**Comment by garris** [comment]
Yes.  Totally makes sense.

**Comment by lewisnyman** [comment]
The only thing left to do here is for you to do here is to head to https://travis-ci.org and login, then enable your repository for testing.

You can also add status images to the Readme so it's easy to tell if the latest changes broke the script http://docs.travis-ci.com/user/status-images/

**Comment by garris** [comment]
Done and done!
screen shot 2015-01-31 at 10 04 13 am

**Pull request merged**
