### PR TITLE
Config object support with Docker

### PR DESCRIPTION
**Pull request by engelfrost**
Solves [garris#987](https://github.com/garris/BackstopJS/issues/987).

It's not possible to pass an object literal via command line to Docker. A config is passed like this: `--config=path-to-config.json`. So the Docker runner assumes that we're using a config file. Currently an object literal evaluated to `--config=[object Object]`.

This is fixed by saving the object as a JSON file (`backstop.config-for-docker.json`) and letting the `config` option point to that file. When the Docker process `exit`s the file is removed, _unless_ the `debug: true` option is passed. Not sure if the debugging thing is actually a good idea.

Does the Docker process always send an `exit` event, even when there is an `error`? If not, the temporary file should also be removed when there is an error.

### CODE REVIEW

**Comment by brownbl1** [comment]
We're running into this issue as well. Any chance this can be merged soon?

**Comment by brownbl1** [comment]
We've tested this locally and in our CI environment and it's working well for us, so I definitely vote on merging! Thanks @engelfrost!

**Comment by garris** [comment]
BTW:  Thanks for this PR!  Will work on getting this in after version 4 releases and any issues are sorted out.

**Comment by webnovationNET** [comment]
Do you have ETA for this fix?

**Comment by garris** [comment]
Merged to master! This still needs to be validated -- so it would be great if someone could kick the tires and add a mocha test for it.   

Thanks everyone for your patience -- many apologies for the delay.  

You are awesome.

**Pull request merged**
