### PR TITLE
Add Editor Config + JSHint + Travis

### PR DESCRIPTION
**Pull request by felquis**
Related to #11 

I worked a bit on it. I added .editorconfig, developer must use a [plugin for the IDE](http://editorconfig.org/#download).

With JSHint was hard, a lot of unused variable that I'm not sure if I can remove, so, I've set [undef](https://github.com/felquis/BackstopJS/commit/f8a5fa33644e14b1b9f45f2fb767343208a9d111#diff-4d5aa81bf4f18104bb6ea53a8b5d1f43R15) property to false

To use travis-ci, you can login with github in https://travis-ci.org, and active travis to BackstopJS, then each push and pull request, Travis (currently), will install node modules and run `gulp lint`, if some error appear in this test travis will warn you about the error in the pull request. ([Here is an example](https://travis-ci.org/felquis/BackstopJS/builds/43340436))

Do you like it?

### CODE REVIEW

**Comment by lewisnyman** [comment]
Maybe split up the changes into separate pull requests? The editor config one is simply removing white space.

If we commit the Travis CI file first, then we can set up the automated tests to ensure the code improvements don't break anything.

**Comment by lewisnyman** [comment]
@felquis Would you be happy to close this pull request and submit separate pull requests for the .editorconfig and JSHint?

**Comment by YuliaTsareva** [comment]
Any news on this pull request?
I think it would be useful to merge at least .editorconfig and then little by little update scripts. If you don't mind I can make separate pull request.

**Comment by garris** [comment]
@YuliaTsareva That would be great!

BTW: I am bumping the version number tomorrow and your PR will be in there.

**Comment by YuliaTsareva** [comment]
@garris  great news!

**Comment by YuliaTsareva** [comment]
@garris A little bit offtopic, but I wonder if you have any reason not to separate compare/index.html into index.html + js file + css file like I did there https://github.com/garris/BackstopJS/compare/master...YuliaTsareva:zoom-images
I think it would make life much easier :) I can make pull request it without my zoom.

**Comment by garris** [comment]
@YuliaTsareva  I originally wrote the core of the app as an internal tool in a few hours and made it as simple as possible -- so there are a lot of things that really should be there that still aren't so I am more than happy to pull in your improvements!  Please go ahead and send a PR -- I would like to see it with the zoom also so please keep it in if you think it is an improvement.   Thank you very much for your help!  It is great to know we are directly contributing to developer happiness :)

**Comment by YuliaTsareva** [comment]
@garris You know my zoom needs jquery, so let's for now leave it without zoom.

**Comment by garris** [comment]
oh crap.  forgot about that.   good call.  thanks.

**Comment by felquis** [comment]
I haven't fixed the warnings, run `gulp jscs` to see them :)

**Pull request closed without merging**
