### PR TITLE
Selector expansion

### PR DESCRIPTION
**Pull request by nobso**
You can find all the details about this feature PR at https://github.com/garris/BackstopJS/pull/249

### CODE REVIEW

**Comment by garris** [comment]
@nobso Can you also target the PR against version 2.0 as well.   Master has not been migrated to 2.0 yet.

**Comment by nobso** [comment]
Ok.

**Comment by garris** [comment]
Feature is in master.   Please review/comment as needed.   Thank you!

**Comment by garris** [comment]
@nobso This feature is now in master with very positive feedback from beta testers.   It will be released soon.  Please reopen and/or let me know if you think it needs anything else.   And thank you very much for the contribution -- it's already creating developer happiness!

**Pull request closed without merging**
